version: '3'
services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    labels:
      - traefik.enable=false
    volumes:
      - postgres:/var/lib/postgresql/data
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:${ODOO_VERSION}
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - /home/docker/${PROJECT_NAME}/data:/opt/data
      - /home/docker/${PROJECT_NAME}/addons:/opt/addons
      - /home/docker/odoo_addons_community/${ODOO_VERSION}:/opt/addons_community
    command: ./odoo-bin -c /opt/config/odoo.conf --db_host=${PROJECT_NAME}_db -i base -d odoo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo-http.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.odoo-http.entrypoints=web
      - traefik.http.routers.odoo-http.service=odoo-http
      - traefik.http.services.odoo-http.loadbalancer.server.port=8069
      - traefik.http.routers.odoo-http.middlewares=redirect@file
      - traefik.http.routers.odoo-websecure.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.odoo-websecure.entrypoints=websecure
      - traefik.http.routers.odoo-websecure.service=odoo-websecure
      - traefik.http.routers.odoo-websecure.tls.certresolver=le
      - traefik.http.routers.odoo-websecure.middlewares=gzip
      - traefik.http.services.odoo-websecure.loadbalancer.server.port=8069
      - traefik.http.routers.odoo-im-websecure.rule=Host(`${PROJECT_URL}`) && (PathPrefix(`/longpooling`))
      - traefik.http.routers.odoo-im-websecure.entrypoints=websecure
      - traefik.http.routers.odoo-im-websecure.service=odoo-im-websecure
      - traefik.http.routers.odoo-im-websecure.tls.certresolver=le
      - traefik.http.routers.odoo-im-websecure.middlewares=gzip,sslheader
      - traefik.http.services.odoo-im-websecure.loadbalancer.server.port=8072
      # middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=websecure

volumes:
    postgres:

networks:
  default:
    external:
      name: proxy