version: '3'
services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    labels:
      - traefik.enable=false
    volumes:
      - postgres:/var/lib/postgresql/data
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:${ODOO_VERSION}
    links:
      - db:${PROJECT_NAME}_db
    ports:
      - ${HTTP_PORT}:8069
      - ${POLL_PORT}:8072
    volumes:
      - /home/docker/${PROJECT_NAME}/data:/opt/data
      - /home/docker/${PROJECT_NAME}/config:/opt/config
      - /home/docker/${PROJECT_NAME}/addons:/opt/addons
      - /home/docker/odoo_addons_community/${ODOO_VERSION}:/opt/addons_community
    command: ./odoo-bin -c /opt/config/odoo.conf --db_host=${PROJECT_NAME}_db -i base -d odoo --http-port=${HTTP_PORT} --longpolling-port=${POLL_PORT}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-http.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}-http.service=${PROJECT_NAME}-http
      - traefik.http.services.${PROJECT_NAME}-http.loadbalancer.server.port=${HTTP_PORT}
      - traefik.http.routers.${PROJECT_NAME}-websecure.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.service=${PROJECT_NAME}-websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.middlewares=gzip
      - traefik.http.services.${PROJECT_NAME}-websecure.loadbalancer.server.port=${HTTP_PORT}
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.rule=Host(`${PROJECT_URL}`) && (PathPrefix(`/longpooling`))
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.service=${PROJECT_NAME}-poll-websecure
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.middlewares=gzip,sslheader
      - traefik.http.services.${PROJECT_NAME}-poll-websecure.loadbalancer.server.port=${POLL_PORT}
      # middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=websecure

volumes:
    postgres:

networks:
  default:
    external:
      name: proxy