version: '3'
services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres:/var/lib/postgresql/data
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:${VERSION}
    volumes:
      - /home/docker/${PROJECT_NAME}/data:/opt/data
      - /home/docker/${PROJECT_NAME}/config/odoo.cfg:/opt/odoo.conf
      - /home/docker/${PROJECT_NAME}/addons:/opt/addons
      - /home/docker/odoo_addons_community/${VERSION}:/opt/addons_community
    command: ./odoo-bin -c /opt/odoo.conf --load-language=fr_FR --language=fr_FR
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers${PROJECT_NAME}_web_secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.rule=Host(`${PROJECT_URL}`) "
      - "traefik.http.routers.${PROJECT_NAME}_web_secure.service=${PROJECT_NAME}_web_secure"
      - "traefik.http.services.${PROJECT_NAME}_web_secure.loadbalancer.server.port=8069"
      - "traefik.http.routers.${PROJECT_NAME}_poll_secure.rule=Host(`${PROJECT_URL}`) && PathPrefix(`/longpolling`)`)"
      - "traefik.http.routers.${PROJECT_NAME}_poll_secure.service=${PROJECT_NAME}_poll"
      - "traefik.http.services.${PROJECT_NAME}_poll_secure.loadbalancer.server.port=8072"
    external_links:
      - "traefik:${PROJECT_URL}" #FOR CSS IN REPORTS

volumes:
    postgres:

networks:
  default:
    external:
      name: proxy