version: '3'
services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:12.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres:/var/lib/postgresql/data
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:${VERSION}
    volumes:
      - /home/docker/${PROJECT_NAME}/data:/opt/data
      - /home/docker/${PROJECT_NAME}/config/:/opt/config
      - /home/docker/${PROJECT_NAME}/addons:/opt/addons
      - /home/docker/odoo_addons_community/${VERSION}:/opt/addons_community
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}_web.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_web.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}_web.service=${PROJECT_NAME}_web
      - traefik.http.services.${PROJECT_NAME}_web.loadbalancer.server.port=8069
      - traefik.http.routers.${PROJECT_NAME}_websecure.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}_websecure.service=${PROJECT_NAME}_websecure
      - traefik.http.routers.${PROJECT_NAME}_websecure.middlewares=gzip
      - traefik.http.services.${PROJECT_NAME}_websecure.loadbalancer.server.port=8069
      - traefik.http.routers.${PROJECT_NAME}_poll_websecure.rule=Host(`${PROJECT_URL}`) && (PathPrefix(`/longpolling`))
      - traefik.http.routers.${PROJECT_NAME}_poll_websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}_poll_websecure.service=${PROJECT_NAME}_poll_websecure
      - traefik.http.routers.${PROJECT_NAME}_poll_websecure.middlewares=gzip,sslheader
      - traefik.http.services.${PROJECT_NAME}_poll_websecure.loadbalancer.server.port=8072

      # middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
    external_links:
      - "traefik:${PROJECT_NAME}" #FOR CSS IN REPORTS

volumes:
    postgres:

networks:
  default:
    external:
      name: proxy