version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pgadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.pgadmin-secure.rule=Host(`pgadmin.${DOMAIN}`)"
      - "traefik.http.routers.pgadmin-secure.service=pgadmin"
      - "traefik.http.middlewares.pgadmin-secure.redirectscheme.scheme=https"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

volumes:
    postgres:
    pgadmin:

