version: '3'
services:
  db:
    container_name: postgres
    image: postgres:12.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres:

networks:
  default:
    external:
      name: proxy