version: '3.1'
services:
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:17.0
    privileged: true
    user: root
    environment:
      HOST: ${PROJECT_NAME}_db
      USER: odoo      
      PASSWORD: odoo
    depends_on:
      - db
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${HTTP_PORT}:8069
      - ${WEBSOCKET_PORT}:8072
    command: odoo  -i base -d odoo -c /etc/odoo/myodoo.conf --http-port=${HTTP_PORT} --longpolling-port=${WEBSOCKET_PORT}  --load-language=fr_FR --language=fr_FR
    volumes:
      - /home/docker/${PROJECT_NAME}/filestore:/var/lib/odoo
      - /home/docker/${PROJECT_NAME}/config:/etc/config
      - /home/docker/${PROJECT_NAME}/addons:/mnt/addons
      - /home/docker/odoo_addons_community/${ODOO_VERSION}:/mnt/addons_community
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-http.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}-http.service=${PROJECT_NAME}-http
      - traefik.http.services.${PROJECT_NAME}-http.loadbalancer.server.port=${HTTP_PORT}
      - traefik.http.routers.${PROJECT_NAME}-websecure.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.service=${PROJECT_NAME}-websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.middlewares=gzip
      - traefik.http.services.${PROJECT_NAME}-websecure.loadbalancer.server.port=${HTTP_PORT}      
      - traefik.http.routers.${PROJECT_NAME}-websocket-websecure.rule=Host(`${PROJECT_URL}`) && Path(`/websocket`)
      - traefik.http.routers.${PROJECT_NAME}-websocket-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-websocket-websecure.service=${PROJECT_NAME}-websocket-websecure
      - traefik.http.routers.${PROJECT_NAME}-websocket-websecure.middlewares=gzip,sslheader
      - traefik.http.services.${PROJECT_NAME}-websocket-websecure.loadbalancer.server.port=${WEBSOCKET_PORT}
      # middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=websecure
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:15-bullseye
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-15:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data-15:
  
networks:
  default:
    external:
      name: proxy
