version: '3.1'
services:
  odoo:
    container_name: ${PROJECT_NAME}_odoo
    image: nithwith/odoo:${ODOO_VERSION}
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${HTTP_PORT}:8069
      - ${POLL_PORT}:8072
    command: odoo -c /etc/odoo/myodoo.conf -i base -d ${PROJECT_NAME} 
    volumes:
      - /home/docker/${PROJECT_NAME}/filestore:/var/lib/odoo
      - /home/docker/${PROJECT_NAME}/config:/etc/config
      - /home/docker/${PROJECT_NAME}/addons:/mnt/addons
      - /home/docker/odoo_addons_community/${ODOO_VERSION}:/mnt/addons_community
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}-http.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-http.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}-http.service=${PROJECT_NAME}-http
      - traefik.http.services.${PROJECT_NAME}-http.loadbalancer.server.port=${HTTP_PORT}
      - traefik.http.routers.${PROJECT_NAME}-websecure.rule=Host(`${PROJECT_URL}`)
      - traefik.http.routers.${PROJECT_NAME}-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.service=${PROJECT_NAME}-websecure
      - traefik.http.routers.${PROJECT_NAME}-websecure.middlewares=gzip
      - traefik.http.services.${PROJECT_NAME}-websecure.loadbalancer.server.port=${HTTP_PORT}      
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.rule=Host(`${PROJECT_URL}`) && (PathPrefix(`/longpolling`))
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.service=${PROJECT_NAME}-poll-websecure
      - traefik.http.routers.${PROJECT_NAME}-poll-websecure.middlewares=gzip,sslheader
      - traefik.http.services.${PROJECT_NAME}-poll-websecure.loadbalancer.server.port=${POLL_PORT}
      # middlewares
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=websecure
volumes:
  odoo-web-data:
  
networks:
  default:
    external:
      name: proxy
